// Cod_um
let
    #"Requisicao" = 
        (numeroPagina) =>
            Json.Document(
                Web.Contents("http://localhost:8080?page=1",
                    [
                        RelativePath = "/medicos",
                        Query = [
                            page = Number.ToText(numeroPagina)
                        ]
                    ]
                )
            )[content],

    #"Total Paginas" = 
        Json.Document(
            Web.Contents("http://localhost:8080?page=1",
                [
                    RelativePath = "/medicos",
                    Query = [
                        page = "1"
                    ]
                ]
            )
        )[totalPages],

    #"Lista Paginas" = {0 .. #"Total Paginas"-1},

    #"Lista Dados" = List.Transform(#"Lista Paginas", each {_, #"Requisicao"(_)}),

    #"Table" =
        Table.TransformColumns(
            Table.ExpandRecordColumn( 
                Table.ExpandListColumn(
                    #table(
                        type table 
                        [ Pagina = text, Dados = list],
                        #"Lista Dados"
                    ),
                    "Dados"
                ),
                "Dados",
                {"id", "nome", "email", "crm", "especialidade"},
                {"Id", "Nome", "E-mail", "CRM", "Especialidade"}
            ),
            {
                "Nome",
                each Text.FromBinary(Text.ToBinary(_, 1252), TextEncoding.Utf8)
            }
        )
in
    #"Table"